services:
  - type: web
    name: registro-cosecha-app
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip>=22.0.0
      python -m pip install --upgrade setuptools>=65.0.0 wheel>=0.38.0
      python -m pip cache purge
      python -m pip install --no-cache-dir --prefer-binary --timeout 1000 -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.fileWatcherType none --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_PREFER_BINARY
        value: 1
      - key: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
