services:
  - type: web
    name: registro-cosecha-app
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.fileWatcherType none
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_PREFER_BINARY
        value: 1
